apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingressistema
  namespace: prod
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: svcsistemanoticias
          servicePort: 80
        path: /